### ISSUE TITLE
no branch named "d1-wip-v5.18-rc1"

### ISSUE THREAD

**Issue by sunshine-lcc** [tmolteno/d1_build#11]
Linux no branch named "d1-wip-v5.18-rc1". I wonder if the dockerfile is out of date? can you update it to the newest?

**Comment by tmolteno** [comment]
I will have a look. Thanks for the report.

**Comment by tmolteno** [comment]
I have tried a clean build here using

    docker-compose build --no-cache dock

And it seems to work. Can you provide the terminal output you are seeing?
